export const CREATE_REMINDER = "CREATE_REMINDER";
export const UPDATE_REMINDER = "UPDATE_REMINDER";
export const DELETE_REMINDER = "DELETE_REMINDER";
export const SET_REMINDERS = "SET_REMINDERS";
export const GET_REMINDERS = "GET_REMINDERS";
export const FETCH_REMINDERS_FAILED = "FETCH_REMINDERS_FAILED";
export const CREATE_REMINDER_SUCCESS = "CREATE_REMINDER_SUCCESS";
export const CREATE_REMINDER_FAIL = "CREATE_REMINDER_FAIL";
export const DELETE_REMINDER_SUCCESS = "DELETE_REMINDER_SUCCESS";
export const DELETE_REMINDER_FAIL = "DELETE_REMINDER_FAIL";

export const CREATE_LOCATION = "CREATE_LOCATION";
export const UPDATE_LOCATION = "UPDATE_LOCATION";
export const DELETE_LOCATION = "DELETE_LOCATION";
export const SET_LOCATIONS = "SET_LOCATIONS";
export const GET_LOCATIONS = "GET_LOCATIONS";
export const SET_ACTIVE_LOCATION_ID = "SET_ACTIVE_LOCATION_ID";
export const FETCH_LOCATIONS_FAILED = "FETCH_LOCATIONS_FAILED";
export const CREATE_LOCATION_SUCCESS = "CREATE_LOCATION_SUCCESS";
export const CREATE_LOCATION_FAIL = "CREATE_LOCATION_FAIL";
export const DELETE_LOCATION_SUCCESS = "DELETE_LOCATION_SUCCESS";
export const DELETE_LOCATION_FAIL = "DELETE_LOCATION_FAIL";

export const SET_GROUPS = "SET_GROUPS";
export const FETCH_GROUPS_FAILED = "FETCH_GROUPS_FAILED";

export const SET_USERS = "SET_USERS";
export const FETCH_USERS_FAILED = "FETCH_USERS_FAILED";

export const LOGIN_REQUEST = 'USERS_LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'USERS_LOGIN_FAILURE';

export const REGISTER_REQUEST = 'USERS_REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'USERS_REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'USERS_REGISTER_FAILURE';

// export const ALERT_SUCCESS = 'ALERT_SUCCESS';
// export const ALERT_ERROR = 'ALERT_ERROR';
// export const ALERT_CLEAR = 'ALERT_CLEAR';




