export const CLEAN_REMINDERERROR = "CLEAN_REMINDERERROR";
export const CREATE_REMINDER = "CREATE_REMINDER";
export const DELETE_REMINDER = "DELETE_REMINDER";
export const SET_REMINDERS = "SET_REMINDERS";
export const GET_REMINDERS = "GET_REMINDERS";
export const FETCH_REMINDERS_FAILED = "FETCH_REMINDERS_FAILED";
export const CREATE_REMINDER_SUCCESS = "CREATE_REMINDER_SUCCESS";
export const CREATE_REMINDER_FAIL = "CREATE_REMINDER_FAIL";
export const DELETE_REMINDER_SUCCESS = "DELETE_REMINDER_SUCCESS";
export const DELETE_REMINDER_FAIL = "DELETE_REMINDER_FAIL";

export const CREATE_LOCATION = "CREATE_LOCATION";
export const UPDATE_LOCATION = "UPDATE_LOCATION";
export const DELETE_LOCATION = "DELETE_LOCATION";
export const SET_LOCATIONS = "SET_LOCATIONS";
export const GET_LOCATIONS = "GET_LOCATIONS";
export const SET_ACTIVE_LOCATION_ID = "SET_ACTIVE_LOCATION_ID";
export const FETCH_LOCATIONS_FAILED = "FETCH_LOCATIONS_FAILED";
export const CREATE_LOCATION_SUCCESS = "CREATE_LOCATION_SUCCESS";
export const CREATE_LOCATION_FAIL = "CREATE_LOCATION_FAIL";
export const UPDATE_LOCATION_SUCCESS = "UPDATE_LOCATION_SUCCESS";
export const UPDATE_LOCATION_FAIL = "UPDATE_LOCATION_FAIL";
export const DELETE_LOCATION_SUCCESS = "DELETE_LOCATION_SUCCESS";
export const DELETE_LOCATION_FAIL = "DELETE_LOCATION_FAIL";

export const SET_GROUPS = "SET_GROUPS";
export const FETCH_GROUPS_FAILED = "FETCH_GROUPS_FAILED";

export const CREATE_USER = "CREATE_USER";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";
export const SET_USERS = "SET_USERS";
export const FETCH_USERS_FAILED = "FETCH_USERS_FAILED";
export const SET_GLOBAL_USERS = "SET_GLOBAL_USERS";
export const FETCH_GLOBAL_USERS_FAILED = "FETCH_GLOBAL_USERS_FAILED";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL"

export const LOGIN_REQUEST = 'USERS_LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'USERS_LOGIN_FAILURE';

export const REGISTER_REQUEST = 'USERS_REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'USERS_REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'USERS_REGISTER_FAILURE';

export const USERME_REQUEST = 'USERME_REQUEST';
export const USERME_SUCCESS = 'USERME_SUCCESS';
export const USERME_FAILURE = 'USERME_FAILURE';


export const USERINFO_REQUEST = 'USERINFO_REQUEST';
export const USERINFO_SUCCESS = 'USERINFO_SUCCESS';
export const USERINFO_FAILURE = 'USERINFO_FAILURE';


export const CREATEGROUP_REQUEST = 'CREATEGROUP_REQUEST';
export const CREATEGROUP_SUCCESS = 'CREATEGROUP_SUCCESS';
export const CREATEGROUP_FAILURE = 'CREATEGROUP_FAILURE';


export const CREATEUSERGROUP_REQUEST = 'CREATEUSERGROUP_REQUEST';
export const CREATEUSERGROUP_SUCCESS = 'CREATEUSERGROUP_SUCCESS';
export const CREATEUSERGROUP_FAILURE = 'CREATEUSERGROUP_FAILURE';


export const CREATE_USERGROUPBULK_REQUEST = 'CREATE_USERGROUPBULK_REQUEST';
export const CREATE_USERGROUPBULK_SUCCESS = 'CREATE_USERGROUPBULK_SUCCESS';
export const CREATE_USERGROUPBULK_FAILURE = 'CREATE_USERGROUPBULK_FAILURE';


export const BULKLOCATION_REQUEST = 'BULKLOCATION_REQUEST';
export const BULKLOCATION_SUCCESS = 'BULKLOCATION_SUCCESS';
export const BULKLOCATION_FAILURE = 'BULKLOCATION_FAILURE';


export const CALENDAR_BULKUPDATE_REQUEST = 'CALENDAR_BULKUPDATE_REQUEST';
export const CALENDAR_BULKUPDATE_SUCCESS = 'CALENDAR_BULKUPDATE_SUCCESS';
export const CALENDAR_BULKUPDATE_FAILURE = 'CALENDAR_BULKUPDATE_FAILURE';



export const WAITING_FOR_APPROVE_REMINDERS_REQUEST = 'WAITING_FOR_APPROVE_REMINDERS_REQUEST ';
export const WAITING_FOR_APPROVE_REMINDERS_SUCCESS = 'WAITING_FOR_APPROVE_REMINDERS_SUCCESS';
export const WAITING_FOR_APPROVE_REMINDERS_FAILURE = 'WAITING_FOR_APPROVE_REMINDERS_FAILURE ';


export const APPROVED_REMINDERS_REQUEST = 'APPROVED_REMINDERS_REQUEST ';
export const APPROVED_REMINDERS_SUCCESS = 'APPROVED_REMINDERS_SUCCESS';
export const APPROVED_REMINDERS_FAILURE = 'APPROVED_REMINDERS_FAILURE ';






export const SET_CURMONTH = 'SET_CURMONTH';






