export const REMINDER_CLEAN_FLAGS = "REMINDER_CLEAN_FLAGS";
export const CREATE_REMINDER = "CREATE_REMINDER";
export const DELETE_REMINDER = "DELETE_REMINDER";
export const UPDATE_REMINDER = "UPDATE_REMINDER";
export const SET_REMINDERS = "SET_REMINDERS";
export const GET_REMINDERS = "GET_REMINDERS";
export const SET_REMINDERS_FOR_CRUD = "SET_REMINDERS_FOR_CRUD";
export const FETCH_REMINDERS_FAILED = "FETCH_REMINDERS_FAILED";
export const CREATE_REMINDER_SUCCESS = "CREATE_REMINDER_SUCCESS";
export const CREATE_REMINDER_FAIL = "CREATE_REMINDER_FAIL";
export const DELETE_REMINDER_SUCCESS = "DELETE_REMINDER_SUCCESS";
export const DELETE_REMINDER_FAIL = "DELETE_REMINDER_FAIL";
export const UPDATE_REMINDER_START = "UPDATE_REMINDER_START";
export const UPDATE_REMINDER_SUCCESS = "UPDATE_REMINDER_SUCCESS";
export const UPDATE_REMINDER_FAIL = "UPDATE_REMINDER_FAIL";
export const START_DOWNLOADING = "START_DOWNLOADING";
export const END_DOWNLOADING = "END_DOWNLOADING";

export const CREATE_LOCATION = "CREATE_LOCATION";
export const UPDATE_LOCATION = "UPDATE_LOCATION";
export const DELETE_LOCATION = "DELETE_LOCATION";
export const SET_LOCATIONS = "SET_LOCATIONS";
export const GET_LOCATIONS = "GET_LOCATIONS";
export const SET_ACTIVE_LOCATION_ID = "SET_ACTIVE_LOCATION_ID";
export const FETCH_LOCATIONS_FAILED = "FETCH_LOCATIONS_FAILED";
export const CREATE_LOCATION_SUCCESS = "CREATE_LOCATION_SUCCESS";
export const CREATE_LOCATION_FAIL = "CREATE_LOCATION_FAIL";
export const UPDATE_LOCATION_SUCCESS = "UPDATE_LOCATION_SUCCESS";
export const UPDATE_LOCATION_FAIL = "UPDATE_LOCATION_FAIL";
export const DELETE_LOCATION_SUCCESS = "DELETE_LOCATION_SUCCESS";
export const DELETE_LOCATION_FAIL = "DELETE_LOCATION_FAIL";
export const REORDER_LOCATION = "REORDER_LOCATION";
export const LOCATION_CLEAN_FLAGS = 'LOCATION_CLEAN_FLAGS';

export const SET_GROUPS = "SET_GROUPS";
export const FETCH_GROUPS_FAILED = "FETCH_GROUPS_FAILED";

export const CREATE_USER = "CREATE_USER";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";
export const SET_USERS = "SET_USERS";
export const SET_GROUP_USERS_COUNT = "SET_GROUP_USERS_COUNT";
export const FETCH_USERS_FAILED = "FETCH_USERS_FAILED";
export const SET_GLOBAL_USERS = "SET_GLOBAL_USERS";
export const FETCH_GLOBAL_USERS_FAILED = "FETCH_GLOBAL_USERS_FAILED";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL"

export const LOGIN_REQUEST = 'USERS_LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'USERS_LOGIN_FAILURE';

export const REGISTER_REQUEST = 'USERS_REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'USERS_REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'USERS_REGISTER_FAILURE';

export const USERME_REQUEST = 'USERME_REQUEST';
export const USERME_SUCCESS = 'USERME_SUCCESS';
export const USERME_FAILURE = 'USERME_FAILURE';

export const USERINFO_REQUEST = 'USERINFO_REQUEST';
export const USERINFO_SUCCESS = 'USERINFO_SUCCESS';
export const USERINFO_FAILURE = 'USERINFO_FAILURE';
export const USER_INFO_CLEAN_FLAGS = 'USER_INFO_CLEAN_FLAGS';
export const USER_CLEAN_FLAGS = 'USER_CLEAN_FLAGS';

export const UPDATE_USERINFO_REQUEST = 'UPDATE_USERINFO_REQUEST';
export const UPDATE_USERINFO_SUCCESS = 'UPDATE_USERINFO_SUCCESS';
export const UPDATE_USERINFO_FAILURE = 'UPDATE_USERINFO_FAILURE';

export const CREATEGROUP_REQUEST = 'CREATEGROUP_REQUEST';
export const CREATEGROUP_SUCCESS = 'CREATEGROUP_SUCCESS';
export const CREATEGROUP_FAILURE = 'CREATEGROUP_FAILURE';

export const CREATE_USERGROUPBULK_REQUEST = 'CREATE_USERGROUPBULK_REQUEST';
export const CREATE_USERGROUPBULK_SUCCESS = 'CREATE_USERGROUPBULK_SUCCESS';
export const CREATE_USERGROUPBULK_FAILURE = 'CREATE_USERGROUPBULK_FAILURE';

export const UPDATE_USER_GROUP_SUCCESS = 'UPDATE_USER_GROUP_SUCCESS';
export const UPDATE_USER_GROUP_FAILURE = 'UPDATE_USER_GROUP_FAILURE';

export const USER_GROUP_CLEAN_FLAGS = 'USER_GROUP_CLEAN_FLAGS';

export const CREATE_BULK_LOCATION_REQUEST = 'CREATE_BULK_LOCATION_REQUEST';
export const CREATE_BULK_LOCATION_SUCCESS = 'CREATE_BULK_LOCATION_SUCCESS';
export const CREATE_BULK_LOCATION_FAILURE = 'CREATE_BULK_LOCATION_FAILURE';


export const CALENDAR_BULKUPDATE_REQUEST = 'CALENDAR_BULKUPDATE_REQUEST';
export const CALENDAR_BULKUPDATE_SUCCESS = 'CALENDAR_BULKUPDATE_SUCCESS';
export const CALENDAR_BULKUPDATE_FAILURE = 'CALENDAR_BULKUPDATE_FAILURE';


export const UPDATE_PERMISSION_REQUEST = 'UPDATE_PERMISSION_REQUEST';
export const UPDATE_PERMISSION_SUCCESS = 'UPDATE_PERMISSION_SUCCESS';
export const UPDATE_PERMISSION_FAILURE = 'UPDATE_PERMISSION_FAILURE';


export const CREATE_PERMISSION_REQUEST = 'CREATE_PERMISSION_REQUEST';
export const CREATE_PERMISSION_SUCCESS = 'CREATE_PERMISSION_SUCCESS';
export const CREATE_PERMISSION_FAILURE = 'CREATE_PERMISSION_FAILURE';

export const GET_PERMISSIONS_REQUEST = 'GET_PERMISSIONS_REQUEST';
export const GET_PERMISSIONS_SUCCESS = 'GET_PERMISSIONS_SUCCESS';
export const GET_PERMISSIONS_FAILURE = 'GET_PERMISSIONS_FAILURE';

export const GET_APPROVED_PERMISSIONS_REQUEST = 'GET_APPROVED_PERMISSIONS_REQUEST';
export const GET_APPROVED_PERMISSIONS__SUCCESS = 'GET_APPROVED_PERMISSIONS__SUCCESS';
export const GET_APPROVED_PERMISSIONS__FAILURE = 'GET_APPROVED_PERMISSIONS__FAILURE ';


export const CREATE_USER_GROUP_REQUEST = 'CREATE_USER_GROUP_REQUEST';
export const CREATE_USER_GROUP_SUCCESS = 'CREATE_USER_GROUP_SUCCESS';
export const CREATE_USER_GROUP_FAILURE = 'CREATE_USER_GROUP_FAILURE';

export const DELETE_USER_GROUP = 'DELETE_USER_GROUP';
export const DELETE_USER_GROUP_SUCCESS = 'DELETE_USER_GROUP_SUCCESS';
export const DELETE_USER_GROUP_FAIL = 'DELETE_USER_GROUP_FAIL';


export const GET_CALENDARSCOUNT_REQUEST = 'GET_CALENDARSCOUNT_REQUEST';
export const GET_CALENDARSCOUNT_SUCCESS = 'GET_CALENDARSCOUNT_SUCCESS';
export const GET_CALENDARSCOUNT_FAILURE = 'GET_CALENDARSCOUNT_FAILURE';


export const SET_CURMONTH = 'SET_CURMONTH';
